# coding: UTF-8

NEWS_CATEGORY_COMPANYNEWS = "companynews"
NEWS_CATEGORY_IMPORTINFO = "importinfo"

NEW_CATEGORY_CHOICES = (
	(NEWS_CATEGORY_COMPANYNEWS, u"公司新闻"),
	(NEWS_CATEGORY_IMPORTINFO, u"重要通知"),
)

NEWS_MAX_LENGTH = 10000000
