# coding=utf-8

TASK_ALLOCATION_STATUS_CHOICES = (
 ("",u"任务分配状态"),
 (1,u"未分配"),
 (0,u"已分配"),
)

TASK_CONFIRM_STATUS_CHOICES = (
  ("",u"任务完成状态"),
  (1,u"未完成"),
  (0,u"已完成"),
)

TASK_PLAN_STATUS_CHOICES = (
    ("",u"任务计划状态"),
    (1,u"未完成"),
    (0,u"已完成")
)


PRODUCTION_MATERIALREQUISITION_APPLY = 10
PRODUCTION_MATERIALREQUISITION_INDUSTRY = 20
PRODUCTION_MATERIALREQUISITION_STORAGE = 30

PRODUCTION_MATERIALREQUISITION_STATUS_CHOICES=(
    (PRODUCTION_MATERIALREQUISITION_APPLY, u"领料单申请"),
    (PRODUCTION_MATERIALREQUISITION_INDUSTRY, u"领料单工部审核"),
    (PRODUCTION_MATERIALREQUISITION_STORAGE, u"领料单库存审核"),
)
