from storage.models import *
weldrefund = (WeldRefund,"refund_confirm_main","weldrefundconfirm")

STORAGE_CARD_DATA_DICT = {
    "weldrefund":weldrefund,
}

########status for keeper ##########
ENTRY_STATUS_KEEPER_LIST = [ENTRYSTATUS_CHOICES_KEEPER,ENTRYSTATUS_CHOICES_END]
APPLYCARD_STATUS_KEEPER_LIST = [APPLYCARD_KEEPER,APPLYCARD_END]
AUXILIARYTOOL_APPLY_STATUS_KEEPER_LIST = [AUXILIARY_TOOL_APPLY_CARD_KEEPER,AUXILIARY_TOOL_APPLY_CARD_END]
REFUND_STATUS_KEEPER_LIST = [REFUNDSTATUS_CHOICES_KEEPER,REFUNDSTATUS_CHOICES_END]
REFUNDSTATUS_STEEL_KEEPER_LIST = [REFUNDSTATUS_STEEL_CHOICES_KEEPER,REFUNDSTATUS_STEEL_CHOICES_END]
STORAGE_STATUS_KEEPER_LIST = {
    "entry":ENTRY_STATUS_KEEPER_LIST,
    "apply":APPLYCARD_STATUS_KEEPER_LIST,
    "auapply":AUXILIARYTOOL_APPLY_STATUS_KEEPER_LIST,
    "refund":REFUND_STATUS_KEEPER_LIST,
    "steelrefund":REFUNDSTATUS_STEEL_KEEPER_LIST,
}

