# coding: UTF-8

BIDFORM_STATUS_CREATE=10
BIDFORM_STATUS_SELECT_SUPPLIER=20
BIDFORM_STATUS_INVITE_BID=30
BIDFORM_STATUS_PROCESS_FOLLOW=40
BIDFORM_STATUS_CHECK_STORE=50
BIDFORM_STATUS_COMPLETE=60
BIDFORM_STATUS_STOP=-1

BIDFORM_PART_STATUS_CREATE=10
BIDFORM_PART_STATUS_ESTABLISHMENT=20
BIDFORM_PART_STATUS_APPROVED=30
BIDFORM_PART_STATUS_SELECT_SUPPLLER_APPROVED=40
BIDFORM_PART_STATUS_INVITE_BID_APPLY=50
BIDFORM_PART_STATUS_INVITE_BID_BRANCECORPOR_AOORIVED=60
BIDFORM_PART_STATUS_INVITE_BID_BINHAICORPOR_AOORIVED=70
BIDFORM_PART_STATUS_INVITE_BID_BIDINVITATION_AOORIVED=80
BIDFORM_PART_STATUS_INVITE_BID_WINBIDNOTICE_AOORIVED=90
BIDFORM_PART_STATUS_PROCESS_FOLLOW=100
BIDFORM_PART_STATUS_CHECK=110
BIDFORM_PART_STATUS_STORE=120
BIDFORM_PART_STATUS_COMPLETE=130
BIDFORM_PART_STATUS_STOP=-1

BIDFORM_STATUS_CHOICES=(

    (BIDFORM_STATUS_CREATE,u"标单生成"),
    (BIDFORM_STATUS_SELECT_SUPPLIER,u"供应商选择"),
    (BIDFORM_STATUS_INVITE_BID,u"招标"),
    (BIDFORM_STATUS_PROCESS_FOLLOW,u"过程跟踪"),
    (BIDFORM_STATUS_CHECK_STORE,u"检查入库"),
    (BIDFORM_STATUS_COMPLETE,u"标单完成"),
    (BIDFORM_STATUS_STOP,u"标单终止")
    
)

BIDFORM_PART_STATUS_CHOICES=(
    
    (BIDFORM_PART_STATUS_CREATE,u"标单创建"),
    (BIDFORM_PART_STATUS_ESTABLISHMENT,u"标单编制"),
    (BIDFORM_PART_STATUS_APPROVED,u"标单审批"),
    (BIDFORM_PART_STATUS_SELECT_SUPPLLER_APPROVED,u"供应商选择"),
    (BIDFORM_PART_STATUS_INVITE_BID_APPLY,u"招标申请"),
    (BIDFORM_PART_STATUS_INVITE_BID_BRANCECORPOR_AOORIVED,u"分公司领导批准"),
    (BIDFORM_PART_STATUS_INVITE_BID_BINHAICORPOR_AOORIVED,u"滨海公司领导批准"),
    (BIDFORM_PART_STATUS_INVITE_BID_BIDINVITATION_AOORIVED,u"滨海招标办领导批准"),
    (BIDFORM_PART_STATUS_INVITE_BID_WINBIDNOTICE_AOORIVED,u"中标通知书"),
    (BIDFORM_PART_STATUS_PROCESS_FOLLOW,u"进程跟踪"),
    (BIDFORM_PART_STATUS_CHECK,u"标单检验"),
    (BIDFORM_PART_STATUS_STORE,u"标单入库"),
    (BIDFORM_PART_STATUS_COMPLETE,u"标单完成"),
    (BIDFORM_PART_STATUS_STOP,u"标单终止")
)

APPROVED_PASS=0
APPROVED_NOT_PASS=1
APPROVED_RESULT_CHOICES=(
    (APPROVED_PASS,u"通过"),
    (APPROVED_NOT_PASS,u"不通过")
)
IDENTITYERROR = "登录帐号或密码有错误！"

ORDERFORN_STATUS_BEGIN = 0
ORDERFORN_STATUS_ESTABLISHMENT = 1
ORDERFORN_STATUS_FINISH = 2

ORDERFORM_STATUS_CHOICES = (
    (ORDERFORN_STATUS_BEGIN, u"创建中订购单"),
    (ORDERFORN_STATUS_ESTABLISHMENT, u"创建完成订购单"),
    (ORDERFORN_STATUS_FINISH, u"已终止历史订购单"),
)

RECHECK_CHOICE = (
    (True,u"是"),
    (False,u"否"),
)

INVENTORY_TYPE = (
    (0, u"主材定额"),
    (1, u"辅料定额"),
    (2, u"先投件明细"),
    (3, u"外购件明细"),
    (4, u"铸锻件明细"),
)

SELL_TYPE = (
    (0, u"内销"),
    (1, u"外销"),
)

IMPLEMENT_CLASS_CHOICES = (
    (0, u"招标"),
    (1, u"议标"),
)

SEX_CHOICES = (
    (0, u"男"),
    (1, u"女"),
)
INDEX_LIST = tuple(
    (i, str(i)) for i in xrange(1, 11)
)

ARRIVAL_CHECK_FIELDS = {"mat":"material_confirm","sof":"soft_confirm","ins":"inspect_confirm"}

REVIEW_COMMENTS_CHOICE_WAIT = -1

REVIEW_COMMENTS_CHOICES = (
    (-1,u"未审核"),
    (0,u"通过"),
    (1,u"不通过"),
)
MAIN_MATERIEL = "main_materiel"
SUPPORT_MATERIEL = "support_materiel"
MATERIEL_CHOICE = (
    (MAIN_MATERIEL, u"主材"),
    (SUPPORT_MATERIEL, u"辅材"),
)

ENTRYTYPE_WELD = 0
ENTRYTYPE_NORMTEILE = 1
ENTRYTYPE_ASSISTTOOL = 2
ENTRYTYPE_FORGING = 4

ENTRYTYPE_CHOICES = (
    (ENTRYTYPE_WELD,u"焊材"),
    (ENTRYTYPE_FORGING,u"锻件"),
    (ENTRYTYPE_NORMTEILE,u"标准件"),
    (ENTRYTYPE_ASSISTTOOL,u"辅助工具"),
)


ENTRYTYPE_BOARD = 0
ENTRYTYPE_BAR = 1

ENTRYTYPE_CHOICES_2 = {
    (ENTRYTYPE_BOARD,u"板材"),
    (ENTRYTYPE_BAR,u"型材"),
}

BOARD_STEEL = 0
BAR_STEEL = 1
STEEL_TYPE = {
    (BOARD_STEEL,u'板材'),
    (BAR_STEEL,u'型材'),
}

WELDING = 0
STEEL = 1
AUXILIARY_TOOL =2
OUTSIDEBUYING =3

MATERIAL_TYPE={
    (WELDING,u'焊材'),
    (STEEL,u'钢材'),
    (AUXILIARY_TOOL,u'辅助工具'),
    (OUTSIDEBUYING,u'外购件'),
}

KILOGRAM = 0
TON = 1
WEIGHT_MANAGEMENT={
    (KILOGRAM,u'千克'),
    (TON,u'顿'),
}

SQUARE_METER = 0

AREA_MANAGEMENT={
    (SQUARE_METER,u'平方米'),
}

METER = 0
CENTIMETER =1

LENGHT_MANAGEMENT={
    (METER,u'米'),
    (CENTIMETER,u"厘米"),
}









PAGE_ELEMENTS = 10



NEWS_CATEGORY_COMPANYNEWS = "companynews"
NEWS_CATEGORY_IMPORTINFO = "importinfo"
NEWS_CATEGORY_DOCUMENTS = "documents"

NEW_CATEGORY_CHOICES = (
    (NEWS_CATEGORY_COMPANYNEWS, u"公司新闻"),
    (NEWS_CATEGORY_IMPORTINFO, u"重要通知"),
)

NEWS_MAX_LENGTH = 10000000
#-------------库存管理----------------#
STORAGESTATUS_PURCHASER = 0
STORAGESTATUS_INSPECTOR = 1
STORAGESTATUS_KEEPER = 2
STORAGESTATUS_REFUNDER = 3
STORAGESTATUS_AUDITOR = 4
STORAGESTATUS_PROPOSER = 5

STORAGESTATUS_END = -2
ENTRYSTATUS_CHOICES = (
    (STORAGESTATUS_PURCHASER,u"待采购员确认"),
    (STORAGESTATUS_INSPECTOR,u"待检查确认"),
    (STORAGESTATUS_KEEPER,u"待库管确认"),
    (STORAGESTATUS_END,u"结束"),
)
ENTRYSTATUS_LIST = [x[0] for x in ENTRYTYPE_CHOICES]
APPLYCARDSTATUS_CHOICES = (
    (STORAGESTATUS_AUDITOR,u"待审核人确认"),
    (STORAGESTATUS_INSPECTOR,u"待检查确认"),
    (STORAGESTATUS_KEEPER,u"待库管确认"),
    (STORAGESTATUS_END,u"结束"),
)
APPLYCARDSTATUS_LIST = [ x[0] for x in APPLYCARDSTATUS_CHOICES ]
APPLYCARD_APPLY=0
APPLYCARD_AUDIT=1
APPLYCARD_INSPECT=2
APPLYCARD_COMMIT=3
APPLYCARD_STATUS_CHOICES=(
        (APPLYCARD_APPLY,u'领用申请'),
        (APPLYCARD_AUDIT,u'领用审核'),
        (APPLYCARD_INSPECT,u'领用检查'),
        (APPLYCARD_COMMIT,u'确认领用'),
        )

AUXILIARY_TOOL_APPLY_CARD_CREATED=0
AUXILIARY_TOOL_APPLY_CARD_APPLYED=1
AUXILIARY_TOOL_APPLY_CARD_COMMITED=2
AUXILIARY_TOOL_APPLY_CARD_STATUS=(
        (AUXILIARY_TOOL_APPLY_CARD_CREATED,u'创建完成'),
        (AUXILIARY_TOOL_APPLY_CARD_APPLYED,u'提交完成'),
        (AUXILIARY_TOOL_APPLY_CARD_COMMITED,u'确认完成'),
        )



REFUNDSTATUS_CHOICES = (
    (STORAGESTATUS_KEEPER,u"库管员"),
    (STORAGESTATUS_END,u"结束"),
)

STORAGEDEPARTMENT_CHOICES=( 
    (-1,u'------'),
    (1,u'部门A'),
    (2,u'部门B'),
    (3,u'部门C'),
    (4,u'部门D'),
)

AUTH_TYPE_CHOICES = (
    (0, u"采购管理"),
    (1, u"库存管理"),
    (2, u"生产管理"),
    (3, u"技术资料管理")
)

AUXILIARY_TOOLS_MODELS_CHOICES=(
        (0,u'碳棒'),
        (1,u'面罩'),
        (2,u'白黑玻璃'),
        (3,u'安全帽'),
    )
STORAGE_ENTRY_TYPE_WELD = 0
STORAGE_ENTRY_TYPE_STEEL = 1

STORAGE_ENTRY_TYPECHOICES=(
    (0,u"焊材"),
    (1,u"钢材"),
)





#技术资料管理
H1 = "0"
J = "2"
R = "3"
ZM = "4"
GY = "5"
DY = "6"
XZ = "7"

CIRCULATION_CHOICES = (
    (H1, "H1"),
    (J, "J"),
    (ZM, "ZM"),
    (R, "R"),
    (GY, "GY"),
    (DY, "DY"),
    (XZ, "XZ"),
)

W = "0"
W1 = "1"
W2 = "2"
W3 = "3"
W4 = "4"
W5 = "5"
W6 = "6"
W25 = "7"
P01 = "8"
P02 = "9"
R = "10"
R1 = "11"
R2 = "12"
Z = "13"
H = "14"
M = "15"
L = "16"
Y = "17"

PROCESSING_CHOICES = (
    (W, "W"),    
    (W1, "W1"),
    (W2, "W2"),
    (W3, "W3"),
    (W4, "W4"),
    (W5, "W5"),
    (W6, "W6"),
    (W25, "W25"),
    (P01, "P01"),
    (P02, "P02"),
    (R, "R"),
    (R1, "R1"),
    (R2, "R2"),
    (Z, "Z"),
    (H, "H"),
    (M, "M"),
    (L, "L"),
    (Y, "Y"),
)


WELD_ROD = "weld_rod"
WELD_WIRE = "weld_wire"
WELD_RIBBON = "weld_ribbon"
WELD_FLUX = "weld_flux"

SHEET = "sheet"
PROFILE = "profile"
PURCHASED = "purchased"
OTHER = "other"
MATERIAL_CATEGORY_CHOICES = (
    (WELD_ROD, u"焊条"),
    (WELD_WIRE, u"焊丝"),
    (WELD_RIBBON, u"焊带"),
    (WELD_FLUX, u"焊剂"),
    (SHEET, u"板材"),
    (PROFILE, u"型材"),
    (PURCHASED, u"外购件"),
    (OTHER, u"其他"),
)

RT = "RT"
UT = "UT"
MT = "MT"
PT = "PT"
VT = "VT"

NONDESTRUCTIVE_INSPECTION_TYPE = (
    (RT, "RT"),
    (UT, "UT"),
    (MT, "MT"),
    (PT, "PT"),
    (VT, "VT"),
)

CYLIDER_TRANSFER_CARD = "cylider_transfer_card"
CAP_TRANSFER_CARD = "cap_transfer_card"

TRANSFER_CARD_TYPE_CHOICES = (
    (CYLIDER_TRANSFER_CARD, u"筒体流转卡"),  
    (CAP_TRANSFER_CARD, u"封头流转卡"),
)


CARD_TYPE_TO_HTML = {
    CYLIDER_TRANSFER_CARD: "techdata/widgets/cylider_transfer_card.html",
    CAP_TRANSFER_CARD: "techdata/widgets/cap_transfer_card.html",
}

MARK_WRITE = "mark_write"
MARK_REVIEW = "mark_review"
MARK_PROOFREAD = "mark_proofread"
MARK_APPROVE = "mark_approve"
MARK_QUOTA = "mark_quota"
MARK_STATISTIC = "mark_statistic"

HEATTREATMENTCARD_ATTR_TEM_START = "temperature_start"
HEATTREATMENTCARD_ATTR_TEM_END = "temperature_end"
HEATTREATMENTCARD_ATTR_TEM_TOP = "temperature_top"
HEATTREATMENTCARD_ATTR_TEM_UP_SPEED = "temperature_up_speed"
HEATTREATMENTCARD_ATTR_TEM_DOWN_SPEED = "temperature_down_speed"
HEATTREATMENTCARD_ATTR_TEM_TIME = "time"

PRODUCTION_PLAN_STAUTS_CHOICES = (
    (1, u"必保"),
    (2, u"在制"),
)
